### PR TITLE
fixes Todo (gui) bg color (high-contrast)

### LINKED ISSUE #52: Todo bright background
Background for `Todo` isn't set manually and looks bad.

todo_pretty
todo_ugly

It looks good when `cursorline` is on, and you're on that line, but it looks bad when you move away.

I'll make pull request when I get home ... I'll just set background for term and gui to `NONE`, and hopefully, that'll do the trick.

cheers 😄

(ps if you don't see it in vim, I'm in gvim 😢 at work)

### PR DESCRIPTION
**Pull request by dylnmc**
fixes #52

### CODE REVIEW

**Comment by arcticicestudio** [comment]
Thanks for your contribution :+1: 

Just adding comparison screenshots for the changelog :wink: 

<p align="center"><strong>Before</strong><br><br><strong>After</strong><br></p>

**Comment by arcticicestudio** [comment]
Just adding comparison screenshots for the changelog :wink: 

<p align="center"><strong>Before</strong><br><br><strong>After</strong><br></p>

**Comment by vincentzhezhang** [comment]
Just a kindly reminder that this hasn't been merged back to master :(

**Comment by arcticicestudio** [comment]
@vincentzhezhang This projects uses gitflow, the `master` branch is the stable branch and only meant for release versions (tags). The main branch is `develop`, it'll be merged into `master` as soon as a version is ready to be released. This PR will be available in version [0.7.0][m] ([Project Board][b]).

[b]: https://github.com/arcticicestudio/nord-vim/projects/10#card-4788504
[m]: https://github.com/arcticicestudio/nord-vim/milestone/9

**Comment by vincentzhezhang** [comment]
Got it, thx!

**Pull request merged**
