### PR TITLE
Removes TSError syntax highlight

### PR DESCRIPTION
**Pull request by georg3tom**
fixes: #269

### CODE REVIEW

**Comment by crispgm** [comment]
This is a great fix 👍🏻

**Comment by arcticicestudio** [comment]
Hi @georg3tom :wave:, thanks for your contribution :+1:

I've posted some questions in #269 about the impact of this change.

**Review by svengreb — APPROVED** [review]

**Review by arcticicestudio — APPROVED** [review]
LGTM after clarifying the impact in #269. Thanks again for this improvement!

**Comment by svengreb** [comment]
<h5 align="center">Release Note Assets</h5>



<p align="center"><strong>Before</strong></p>
<p align="center"></p>

<p align="center"><strong>After</strong></p>
<p align="center"></p>

**Pull request merged**
