### PR TITLE
Adjust fold color to match comment colors

### LINKED ISSUE #38: Adjust fold marker color
> **Related to** #36 

The fold marker are currently using nord1 as foreground color. This is too dark causing them to be unreadable in bright environments and should be adjusted to match the color of comments.

---

\cc @syedelec

### PR DESCRIPTION
**Pull request by arcticicestudio**
> Closes #38 

Adjusted the unreadable fold marker color to match the color of comments.

---

\cc @syedelec

### CODE REVIEW

**Comment by arcticicestudio** [comment]
Adjusted the background color to differ from normal comments and use bold font for better legibility.

gh-40-scrot-fold-background-bold

**Comment by arcticicestudio** [comment]
@dylnmc It's totally fine to use the code review feature and approve PRs. It can be used by everyone and helps the maintainer(s) a lot if users posting feedback this way. The forced review for [code owners](https://github.com/blog/2392-introducing-code-owners) or team members is activated to allow the owner of the repository (or the specific code owner) to review, change or decline a PR before it gets merged by a another user with write privileges without the approve of the code owner.

**Comment by arcticicestudio** [comment]
I'll merge this within the next days to publish the new release version. :date:

**Comment by uwo** [comment]
I apologize if this question reopens the ticket.  My folds are still to dark to read.  I'm using `let g:nord_comment_brightness = 20`.  If you have any advice I'd greatly appreciate it.

**Comment by dylnmc** [comment]
@uwo,

a) I use folds a lot now with `foldmethod=syntax`

b) I don't think that `g:nord_comment_brightness` is affecting the colors for folds. You can manually change them with something like the snippet below, but you're correct that they don't change the folds colors (at least I think).

---

###### snippet

```vim
augroup Nord
    autocmd!
    autocmd ColorScheme nord highlight Folded guifg=#6f7d98
augroup end
```

I agree and think that there should be another setting for folds (since they have a different background color and should be, therefore, brighter.

---

@arcticicestudio every considered doing what solarized does for terminal and instead of duplicating (moist of) the first 8 colors for the latter "bright colors" (you know ... 9-15, as opposed to the first half, 0-8). The concern, obviously, is that many terminals (including st .. unless you hack st.c) set bold colors to "bright" colors (eg, add 8 to the 0-8 color to transpose it to the bright version). They should not do this, and some terminals, like urxvt, one can configure to disable this stupid "feature". Once again, though I point to solarized who does this. We could add different (and user-configurable) tones of this cool gray (the background and its lighter variants) and replace some of the duplicate colors for term. Just a thought, but you'd have to weigh the pros/cons.

cheers and I still can't find a colorscheme better then yours :smiling_imp:,
dylnmc

**Pull request merged**
