### PR TITLE
improve status line visibility

### PR DESCRIPTION
**Pull request by skrobul**
I'd like to propose small change in the `StatusLine` and `StatusLineNC` colors. In current release, these are practically invisible because they have the same color as background.
If this has been done on purpose, please close this PR.

### Before

screen shot 2017-08-23 at 11 39 31 am
### After

screen shot 2017-08-23 at 11 45 25 am

### CODE REVIEW

**Comment by skrobul** [comment]
thanks @francis36012  :)

**Comment by arcticicestudio** [comment]
Thanks for your contribution :+1: 
Sorry for my late reply, I'm currently busy coding a lot of things for my job. I'll take a look at your changes tomorrow to include it in the next release asap if everything looks fine.

**Comment by arcticicestudio** [comment]
Alright, I've checked your changes and noticed that this is related to #37. I've already prepared a change/fix for it, but had no time to propose the possible solutions. Your PR would also fix it, but I'd like to involve other users to decide which change would fit the best.
 
I'll open a poll in #37 so it would be nice if you subscribe to this issue and vote :smile:

**Comment by arcticicestudio** [comment]
> Superseded by #58

@skrobul Thanks again for your PR, we've superseded it in #58 to make this change configurable. Please feel free to subscribe to this PR and review the changes :smile:

**Pull request closed without merging**
