### PR TITLE
Don't load plugin-related things when the relevant plugin isn't installed

### PR DESCRIPTION
**Pull request by jvoisin**
Function calls are expensive in vim-script.
This commit speeds up the processing of colors/nord.vim
in neovim 0.6.1 by almost 50% on my machine, where
none of the supported plugins are installed.

Some plugins provide no easy/straightforward way to be detected, so not all *blocks* are behind conditions, but it's still a significant improvement, and can always be improved in the future.

### CODE REVIEW

**Comment by svengreb** [comment]
Hi @jvoisin :wave:, thanks for your contribution :+1:
I'm currently busy with the preparations for the roadmap and future plan of the whole Nord project, but I'll try to review the changes within the next week(s).

**Review by svengreb — APPROVED** [review]
Only loading the highlighting groups conditionally makes sense and reducing overhead, and therefore improving the performance, is always good :smile:
I've moved some other Neovim exclusive features and supported plugins into a `nvim` block guard even though they [will be deprecated and removed from this port when the official Neovim port is available in a stable version][1].

Thanks again for the contribution 🤘🏼

[1]: https://github.com/arcticicestudio/nord/issues/157#issuecomment-924312218

**Review by arcticicestudio — APPROVED** [review]

**Comment by alappe** [comment]
I get

```
Error detected while processing …/nord-vim/colors/nord.vim:
line  729:
E117: Unknown function: exist
line  862:
E117: Unknown function: exist
```

in `NVIM v0.7.0-dev+1436-gf0d07dcb7`.

**Comment by jvoisin** [comment]
oh.
It's `exists` and not `exist`, meh

**Comment by alappe** [comment]
No problem, thanks for fixing it :)

**Comment by svengreb** [comment]
@alappe Thanks for the report, this has been fixed in #297. Also [see my comment in the PR][1] about what can be learned from this.

[1]: https://github.com/arcticicestudio/nord-vim/pull/297#pullrequestreview-938607567

**Pull request merged**
