### PR TITLE
Fix counterintuitive match paren's highlight

### PR DESCRIPTION
**Pull request by vincentzhezhang**
Made a quick (opionated) fix for https://github.com/arcticicestudio/nord-vim/issues/75

Frame 1
bracket-1

Frame 2
bracket-2

### CODE REVIEW

**Comment by arcticicestudio** [comment]
Thanks for your contribution :+1: 

The changes are good, but there are still some edge cases we need to cover. The PR is only applied for the *gui* mode or when the `termguicolors` option is set, but *cterm* mode is still affected by the problem:

gh-78-scrot-no_cterm_mode

When changing the *cterm* definitions we have to keep in mind that there is no `nord0_term` variable. If we set it to `NONE` (to make it kind of "transparent" and use the main background color) there is another edge case when the `cursorline` option is enabled so only the foreground color of the matching elements would change to `nord8`:

<p align="center"><strong>With <code>cursorline</code> option</strong><br></p>

<p align="center"><strong>Without <code>cursorline</code> option</strong><br></p>

To optimally improve the highlighting for both *gui* and *cterm* mode we should use `nord3` as background color for the matching element which doesn't conflict with the `cursorline` color and also stands out in oder to see the matching element:

<p align="center"><strong>With <code>cursorline</code> option</strong><br></p>

<p align="center"><strong>Without <code>cursorline</code> option</strong><br></p>

gh-78-scrcast-improved

Final definition for the `MatchParen` group:

```vim
call s:hi("MatchParen", s:nord8_gui, s:nord0_gui, s:nord8_term, s:nord3_term, "", "")
```

**Comment by dylnmc** [comment]
Wow! This has been one of the biggest annoyances at work ... trying to find which darn parenthesis I am on.

I think I had guess incorrectly about 90% of the time ... I guess it was fairly unintuitive.

Thanks, thanks, thanks

This is perfect: `call s:hi("MatchParen", s:nord8_gui, s:nord0_gui, s:nord8_term, s:nord3_term, "", "")`

**Comment by dylnmc** [comment]
Is this how it's supposed to look? I just `:PlugUpdate`d

pairs

Looks bad to me?

**Comment by dylnmc** [comment]
Sorry, I totally parroted the wrong thing (even though I swear I tested it.

It should be `call s:hi("MatchParen", s:nord8_gui, s:nord0_gui, s:nord8_term, s:nord3_term, "", "")`

Screenie:

pairs

**Comment by arcticicestudio** [comment]
@dylnmc Your're right, I absolutely don't know why I've changed it to `nord0_gui` instead of `nord3_gui` as background. I'll fix it and ship it as new release version 0.7.1. Thanks for the note :+1:

**Comment by arcticicestudio** [comment]
Fixed in #96

**Comment by dylnmc** [comment]
I have an issue.

This fix is so good, that I think we might have to revert back to the old ways. This is just **too** good.

Should I open an issue?

</joke>

Just kidding! Thanks to both of you. I was just coding and also appreciating that I knew which paren I was on :laughing:

**Pull request merged**
