### PR TITLE
Improve highlights for Neovim LSP

### PR DESCRIPTION
**Pull request by gbrlsnchs**

### CODE REVIEW

**Comment by clason** [comment]
Just a heads-up: these will change again (for the last time?) once https://github.com/neovim/neovim/pull/12655 is merged.

**Comment by clason** [comment]
And now the PR is merged; the new LSP diagnostic highlight names are listed here: https://github.com/neovim/neovim/blob/35325ddac04b1b59b7982797021cdaabdabc87fb/runtime/doc/lsp.txt#L376

**Comment by gbrlsnchs** [comment]
Done. Seems visually nice to me.

**Comment by ojroques** [comment]
The doc mentions that "*Sign, underline and virtual text highlights (by default) are linked to their
corresponding LspDiagnosticsDefault highlight* . Since you're not changing anything for `LspDiagnosticsVirtualText*` `LspDiagnosticsFloating*` `LspDiagnosticsSign*` maybe these lines can be removed?

This is what [onedark.vim](https://github.com/joshdick/onedark.vim/blob/94ff495eac89cea2532d8e0022f67c79a24d9649/colors/onedark.vim#L631-L638) does (disclaimer: it was a PR of mine).

**Comment by gbrlsnchs** [comment]
Done, @ojroques! Thanks for the tip.

**Comment by ojroques** [comment]
Glad to help. I would have kept these lines though since they differ from the defaults:
```vim
call s:hi("LspDiagnosticsUnderlineWarning" , s:nord13_gui, "", s:nord13_term, "", "undercurl", "")
call s:hi("LspDiagnosticsUnderlineError" , s:nord11_gui, "", s:nord11_term, "", "undercurl", "")
call s:hi("LspDiagnosticsUnderlineInformation" , s:nord8_gui, "", s:nord8_term, "", "undercurl", "")
call s:hi("LspDiagnosticsUnderlineHint" , s:nord10_gui, "", s:nord10_term, "", "undercurl", "")
```

The underline text is quite useful to spot warnings/errors.

**Comment by gbrlsnchs** [comment]
You're totally right, my bad. Just included those again.

**Comment by crispgm** [comment]
With `LspDiagnosticsUnderline*` stuffs specified, it would be buggy of showing colors. However, using `LspDiagnosticsDefault*` looks okay. 👌

**Comment by gbrlsnchs** [comment]
> With `LspDiagnosticsUnderline*` stuffs specified, it would be buggy of showing colors. However, using `LspDiagnosticsDefault*` looks okay.

How come? I'm using my fork with this PR applied and everything seems fine.

**Comment by crispgm** [comment]
> > With `LspDiagnosticsUnderline*` stuffs specified, it would be buggy of showing colors. However, using `LspDiagnosticsDefault*` looks okay.
> 
> How come? I'm using my fork with this PR applied and everything seems fine.

okay, works perfectly on another machine. this is weird.

**Comment by gbrlsnchs** [comment]
> > > With `LspDiagnosticsUnderline*` stuffs specified, it would be buggy of showing colors. However, using `LspDiagnosticsDefault*` looks okay.
> > 
> > 
> > How come? I'm using my fork with this PR applied and everything seems fine.
> 
> okay, works perfectly on another machine. this is weird.

Might be your Neovim version maybe? Anyway, good it's working!

**Review by arcticicestudio — APPROVED** [review]
Hi @gbrlsnchs, @clason, @ojroques and @crispgm :wave:, thanks for your contributions :+1:
Also thanks for your patience, the large amount of tasks for the Nord project are really time consuming and free time is kind of rare.

Changes looking good to me 👍🏻
The problems regarding the `undercurl` attribute can be tackled later on in a separate PR by guarding the usage through the [`nord_underline` theme configuration variable][1]. When the terminal is capable to rendering underlines it should also work fine for curly lines.

[1]: https://www.nordtheme.com/docs/ports/vim/configuration#underline-style

**Review by svengreb — APPROVED** [review]

**Pull request merged**
